url: https://justynaipiotrek.pl
baseurl: 

# Site settings
title: Justyna i Piotrek
email: sadlojus@gmail.com
description: "Slubna strona Justyny i Piotrka"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: cd3426
  secondary: dd5549  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Justyna
  pic: 1
  mail: sadlojus@gmail.com
  tel: 503 955 689

- name: Piotrek
  pic: 2
  mail: pbetkier@gmail.com
  tel: 606 650 076
